# Generated by Django 3.2 on 2023-03-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('0', 'MANAGER'), ('1', 'STAFF'), ('2', 'ADMIN')], max_length=10),
        ),
    ]
