# Generated by Django 4.2 on 2023-04-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDefault',
            fields=[
                ('id_inventory_default', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(error_messages={'unique': 'This name has already been registered.'}, max_length=50, unique=True)),
                ('satuan', models.CharField(max_length=20)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
    ]
