# Generated by Django 4.2.1 on 2023-05-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id_resep', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('bahan', models.TextField()),
                ('cara_memasak', models.TextField()),
            ],
        ),
    ]
