# Generated by Django 4.1.7 on 2023-03-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resep',
            name='gambar',
            field=models.ImageField(help_text='Please use .jpg format', upload_to='resep/'),
        ),
    ]
