# Generated by Django 4.2 on 2023-04-12 06:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gedung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id_inventory', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('stok', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('default_request_qty', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=3, max_digits=20)),
                ('satuan', models.CharField(max_length=20)),
                ('id_gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedung.gedung')),
            ],
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nama'), models.OrderBy(django.db.models.functions.text.Lower('id_gedung'), descending=True), name='inventory_gedung_unique', violation_error_message='Inventory sudah terdaftar dalam sistem'),
        ),
    ]
