# Generated by Django 4.2 on 2023-04-15 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gedung', '0001_initial'),
        ('inventory_default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('default_request_qty', models.IntegerField()),
                ('default', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_default.inventorydefault')),
                ('id_gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedung.gedung')),
            ],
        ),
    ]
