# Generated by Django 4.2 on 2023-04-12 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gedung', '0001_initial'),
        ('inventory_default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id_inventory', models.AutoField(primary_key=True, serialize=False)),
                ('stok', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('default_request_qty', models.IntegerField()),
                ('id_gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedung.gedung')),
                ('id_inventory_default', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_default.inventorydefault')),
            ],
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('id_gedung'), models.OrderBy(django.db.models.functions.text.Lower('id_inventory_default'), descending=True), name='inventory_gedung_unique', violation_error_message='Inventory sudah terdaftar dalam sistem'),
        ),
    ]
