# Generated by Django 3.2 on 2023-05-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Riwayat',
            fields=[
                ('id_riwayat', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
                ('price', models.IntegerField()),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
