# Generated by Django 3.2 on 2023-05-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Riwayat',
        ),
    ]
