# Generated by Django 3.2 on 2023-04-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
