# Generated by Django 3.2 on 2023-04-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_request_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
