# Generated by Django 3.2 on 2023-04-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_request_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='token',
            field=models.CharField(default='SEGP1', max_length=5),
        ),
    ]
