# Generated by Django 3.2 on 2023-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_request_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='token',
            field=models.CharField(default='U1JRY', max_length=5),
        ),
    ]
