# Generated by Django 3.2 on 2023-04-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_alter_request_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='created',
            new_name='approved',
        ),
        migrations.AlterField(
            model_name='request',
            name='token',
            field=models.CharField(default='C6JMR', max_length=5),
        ),
    ]
