# Generated by Django 3.2 on 2023-04-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('request', '0008_auto_20230418_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='request',
            name='token',
            field=models.CharField(default='CTGMG', max_length=5),
        ),
    ]
