# Generated by Django 4.2 on 2023-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20230418_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='token',
            field=models.CharField(default='GG1Q4', max_length=5),
        ),
    ]
