# Generated by Django 3.2 on 2023-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0024_alter_request_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='token',
            field=models.CharField(default='L2A3S', max_length=5),
        ),
    ]
