# Generated by Django 4.2 on 2023-04-06 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gedung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventori',
            fields=[
                ('id_inventory', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('stok', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('default_request_qty', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=3, max_digits=20)),
                ('satuan', models.CharField(max_length=20)),
                ('id_gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedung.gedung')),
            ],
        ),
    ]
