# Generated by Django 4.1.7 on 2023-03-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('id_gedung', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
            ],
        ),
    ]
