# Generated by Django 3.2 on 2023-03-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gedung',
            name='status',
            field=models.CharField(default='1', max_length=5),
            preserve_default=False,
        ),
    ]
