# Generated by Django 3.2 on 2023-03-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedung', '0002_gedung_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gedung',
            name='status',
            field=models.CharField(choices=[('0', 'GUDANG PUSAT'), ('1', 'RESTORAN')], max_length=15),
        ),
    ]
